### ISSUE TITLE
Any API/function to perform sampling and output BED?

### ISSUE THREAD

**Issue by fuxialexander** [burcakotlu/GLANET#1]
Thank you for the well-thought program!

I wonder whether there are ways to perform only sampling given a set of regions, and output the sampled files in BED format? I tried to look into the code, but as I'm new to Java, the 15K lines of code is a bit scary for me... Could you please give me some suggestions / directions?

Alex

**Comment by fuxialexander** [comment]
BTW, I want to do that because I'd like to defined a custom evaluation function for p-value, which depend on some metadata in the region set. Seems currently I can't do that with GLANET?

**Comment by burcakotlu** [comment]
Dear fuxialexander,

Thank you for your interest in our tool, GLANET.
You can definitely output the randomly generated intervals for each sampling.
Please keep in mind that writing to files during fork/join framework will slow down the GLANET.
I prefer you to start with minimum number of samplings that is 1000, in our case.

When you clone the code on your local machine, go to Enrichment class,  at line 8886, there is a parameter called writeGeneratedRandomDataMode,
set it to WriteGeneratedRandomDataMode.DO_WRITE_GENERATED_RANDOM_DATA and then when you run GLANET, it will output the randomly generated intervals into files under Output folder.


I hope you got your expected answer.
Best wishes,
Burcak Otlu

**Comment by burcakotlu** [comment]
Dear fuxialexander,

By the way, you can also change the number of samplings internally within the code to any positive integer number you wish.  What I'm saying is that you don't have to set it to 1000.

Best wishes,
Burcak Otlu

**Comment by fuxialexander** [comment]
Thank you for your detailed reply!
